spring:
  redis:
    host: localhost # 默认localhost，可以不用配置
    port: 6379      # 默认6379，可以不用配置
    database: 0    # 默认第0个数据库，可以不用配置
    password: pass4redis#123
    lettuce:
      pool:
        max-active: 8    # 连接池最大连接数(使用负值表示没有限制) 默认为8
        min-idle: 0      # 连接池中的最小空闲连接 默认为 0
        max-idle: 8      # 连接池中的最大空闲连接 默认为8
        max-wait: -1ms   # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1